version = 0.1
[default.deploy.parameters]
stack_name = "MinoriBackDev"
resolve_s3 = true
s3_prefix = "MinoriBackDev"
region = "ap-northeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
